CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED BY 'replpass';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl'@'%';
CREATE USER IF NOT EXISTS 'ha_agent'@'%' IDENTIFIED BY 'replpass';
GRANT SYSTEM_VARIABLES_ADMIN, REPLICATION_SLAVE_ADMIN, REPLICATION CLIENT, PROCESS ON *.* TO 'ha_agent'@'%';
FLUSH PRIVILEGES;
